### ISSUE TITLE
NKSR release for cuda 12?

### ISSUE THREAD

**Issue by rfeinman** [nv-tlabs/XCube#1]
Thanks for the awesome paper and code!

Your README conda environment setup references a directory `ext/nksr-cuda` which does not exist. Where can I find the NKSR package? The pip packages from the [NKSR github](https://github.com/nv-tlabs/NKSR) are built for CUDA 11 and are incompatible with this environment.

Also, just FYI: the [fvdb setup.py script](https://github.com/fwilliams/openvdb/blob/f006533a5bd485af0c38b9c40b784d86b1de3843/fvdb/setup.py) references a github repository (NVIDIA-Omniverse/NanoVDB) that does not exist, or that at least is not public. 

Just a few small fixes and the code should be runnable. Thanks!

**Comment by xrenaa** [comment]
Hi, 
Thanks for your issue! 
We just upload nksr-cuda and you could try it again. 
And for the nanoVDB, we are working on fixing this.

**Comment by rfeinman** [comment]
Thank you! I ran into a few more issues during install that I thought I'd point out.

1. During fvdb install, the setup.py instructs to use c++20, but official pytorch 2.2.0 is built with c++17. So this causes an error.
2. The nksr install expects a folder `openvdb/fvdb/fvdb/include`. However I find that this include directory is not automatically generated by the fvdb install. I had to copy it over manually to the expected location.

**Comment by xrenaa** [comment]
We update fvdb, could you try to install again? Thanks!

**Comment by rfeinman** [comment]
Yes, the nanovdb issue is solved now, thanks! The other 2 fvdb issues still persist (c++20 and missing include dirs) but I was able to figure out work-arounds and I'm sure others will too. Thanks for your quick feedback!

**Comment by yshen47** [comment]
@rfeinman Could you clarify a bit more on which files you copied into folder openvdb/fvdb/fvdb/include? I'm finally able to compile the fvdb, and able to import fvdb in python. But it is not able to compile nksr-cuda, with the follow error (looking like it's related to include directory): 

`
XXX/XCube/ext/nksr-cuda/csrc/meshing/functions.h:3:10: fatal error: fvdb/GridBatch.h: No such file or directory
    3 | #include <fvdb/GridBatch.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by xrenaa** [comment]
Hi @yshen47，
I will also have a look to fix it.

**Comment by rfeinman** [comment]
Hi @yshen47 

I actually just wrote an explanation in issue #2 here: https://github.com/nv-tlabs/XCube/issues/2#issuecomment-2189035531

Does this solve it for you?

**Comment by yshen47** [comment]
yea, i just figured out myself too, thanks

**Comment by xrenaa** [comment]
Hi, we also figure out these issues. Will update fvdb soon.

**Comment by xrenaa** [comment]
For a problemless installation:
```
# Install sparse 3D deep learning framework 
git clone https://github.com/AcademySoftwareFoundation/openvdb.git
cd openvdb
git fetch origin pull/1808/head:feature/fvdb
git checkout feature/fvdb
rm fvdb/setup.py && cp ../assets/setup.py openvdb/fvdb/
cd fvdb && python setup.py develop
cd ../..

# Mesh extraction
cd ext/nksr-cuda
python setup.py develop
cd ../..
```
