### ISSUE TITLE
Can you give a hint about how long would it take to train the model?

### ISSUE THREAD

**Issue by krNeko9t** [nv-tlabs/XCube#11]
Very solid work in 3D generation, and i'd like to know how long would it take to train the model and the GPU resource cost?

**Comment by xrenaa** [comment]
Hi, for ShapeNet case, we train the first stage diffusion model with 8 V100 about two days (longer training will help). And we train the second stage diffusion model about 1 week on 8 V100 (shorter training also looks good).

**Comment by VLadImirluren** [comment]
> Hi, for ShapeNet case, we train the first stage diffusion model with 8 V100 about two days (longer training will help). And we train the second stage diffusion model about 1 week on 8 V100 (shorter training also looks good).

What's the GPU memory of your V100?16 GB? 32GB? If I want to train on one 80GB GPU, How to set the batchsize?(bs = 32 will out of memory)

**Comment by VLadImirluren** [comment]
> > Hi, for ShapeNet case, we train the first stage diffusion model with 8 V100 about two days (longer training will help). And we train the second stage diffusion model about 1 week on 8 V100 (shorter training also looks good).
> 
> What's the GPU memory of your V100?16 GB? 32GB? If I want to train on one 80GB GPU, How to set the batchsize?(bs = 32 will out of memory)

Running on a 80GB A800 ,my GPU memory wanders back and forth between 3000MB and 79000MB, and the GPU utilization wanders back and forth between 0% and 100%. With the first two epochs running completely, the third epoch exploded. What's the situation?

**Comment by xrenaa** [comment]
Hi

**Comment by VLadImirluren** [comment]
> Hi, it seems that you are running the VAE part? For the VAE training, the first few epochs are very unstable. It would be better to finetune pretrained VAE, as indicated [here](https://github.com/nv-tlabs/XCube/blob/main/MISC.md#vae-pretraining).

Thanks a lot!

**Comment by VLadImirluren** [comment]
> Hi, for ShapeNet case, we train the first stage diffusion model with 8 V100 about two days (longer training will help). And we train the second stage diffusion model about 1 week on 8 V100 (shorter training also looks good).

Could you please tell me how long it would take per epochs(VAE and diffusion in coarse and fine stage)? Thanks
