### ISSUE TITLE
Image conditioning

### ISSUE THREAD

**Issue by jclarkk** [nv-tlabs/XCube#13]
Hi, thanks for sharing your awesome work!

Will image conditioning be supported at some point?

**Comment by jclarkk** [comment]
Thanks for the reply and explanation!

**Comment by zzz5y** [comment]
> Hi, thanks for your interest.
> 
> We do not have a concrete plan to release the image conditioning part, so it may take months to merge into the current XCube codebase. However, it is very easy to extend the current codebase to image conditioning. There are two ways we have tried:
> 
> * Use the cross-attention in the diffusion model: for the condition, we use DINOv2 to tokenize the input images and then concatenate with the Plücker coordinates.
> * Unproject the images to dense/sparse voxels and then apply pooling. Then concatenate this feature cube to the input of the diffusion model

Hello,I'm a little curious about how to achieve this.
I try to use datagen to gen voxel data. And put it in the net_model.evauation_api as the coarse net grids,But it doesn't work!

![Image](https://github.com/user-attachments/assets/ff5482a4-0037-4134-aa30-070215c13264)

And then i try to use autoencode model , get the encoded datagen voxel data,and put it in the coarse net grids,but there are some starnge problem

![Image](https://github.com/user-attachments/assets/faca2e23-c4ba-42d0-b733-6a1cd251bd0c)
Can you give me some suggestions?Thank you so much
