### ISSUE TITLE
fvdb setup fails using /lib/. instead of /lib64/. and nksr-cuda setup 'include fvdb error'

### ISSUE THREAD

**Issue by ostjul** [nv-tlabs/XCube#2]
Thanks for the code release and great paper!
The setup of fvdb seems to work fine on my system with one exception, that I could fix. Following your installation instructions on a linux server I experienced the following build error:

`cannot find external/c-blosc/install/lib/libblosc.a: No such file or directory`

A solution that worked for me was changing the path in the setup file. In `openvdb/fvdb/setup.py` line 264:
` (...) extra_objects=['external/c-blosc/install/lib/libblosc.a'] + cudnn_static_libs,`
needs to be changed to
`extra_objects=['external/c-blosc/install/lib64/libblosc.a'] + cudnn_static_libs,`
if the systems default is building the 64bit version in lib64. Otherwise, it fails to find `libblosc.a`.
Seems to be related to an easybuild/GCC compiler issue.

While I can import fvdb python packages now in the nksr-cuda setup `#include <fvdb/GridBatch.h>` doesn't work and I could not figure out the right referencing myself yet.

**Comment by rfeinman** [comment]
@ostjul I had the same problem but was able to fix it by copying the `include` dir from my build folder after the fvdb install. See below for what I ran.

```
cd openvdb/fvdb
cp -R build/lib.linux-x86_64-cpython-39/fvdb/include fvdb/include
```

**Comment by ostjul** [comment]
Thanks a lot @rfeinman, it worked after copying all files from `fvdb/include/nanovdb/nanovdb` to `fvdb/include/nanovdb`

**Comment by xrenaa** [comment]
Hi, this coud also be fix by:
```
# Install sparse 3D deep learning framework 
git clone https://github.com/AcademySoftwareFoundation/openvdb.git
cd openvdb
git fetch origin pull/1808/head:feature/fvdb
git checkout feature/fvdb
rm fvdb/setup.py && cp ../assets/setup.py openvdb/fvdb/
cd fvdb && python setup.py develop
cd ../..

# Mesh extraction
cd ext/nksr-cuda
python setup.py develop
cd ../..
```

**Comment by wenqsun** [comment]
@xrenaa Thanks for your guidelines! I followed the provided instructions and also copied the files as @rfeinman has mentioned before, but I met a problem:
`x86_64-conda-linux-gnu-c++: error: unrecognized command-line option '-march'`
It seems that the c++ version is not suitable, how can I fix this bug?

Thanks for your reply!

**Comment by Luh1124** [comment]
Hello, after following the above steps and running the infer code, I encountered the following error:

`openvdb/fvdb/fvdb/libfvdb.so: undefined symbol: _ZN2at4_ops13scalar_tensor4callERKN3c106ScalarESt8optionalINS2_10ScalarTypeEES6_INS2_6LayoutEES6_INS2_6DeviceEES6_IbE`

Can you please help me solve this issue?

**Comment by VLadImirluren** [comment]
> @ostjul I had the same problem but was able to fix it by copying the `include` dir from my build folder after the fvdb install. See below for what I ran.
> 
> ```
> cd openvdb/fvdb
> cp -R build/lib.linux-x86_64-cpython-39/fvdb/include fvdb/include
> ```

Could you please tell me how to install fvdb? I using pip install fvdb failed.Thanks

**Comment by Luh1124** [comment]
> > @ostjul I had the same problem but was able to fix it by copying the `include` dir from my build folder after the fvdb install. See below for what I ran.
> > ```
> > cd openvdb/fvdb
> > cp -R build/lib.linux-x86_64-cpython-39/fvdb/include fvdb/include
> > `
> 
> Could you please tell me how to install fvdb? I using pip install fvdb failed.Thanks


Solved according to this:

> Hi, this coud also be fix by:
> 
> ```
> # Install sparse 3D deep learning framework 
> git clone https://github.com/AcademySoftwareFoundation/openvdb.git
> cd openvdb
> git fetch origin pull/1808/head:feature/fvdb
> git checkout feature/fvdb
> rm fvdb/setup.py && cp ../assets/setup.py openvdb/fvdb/
> cd fvdb && python setup.py develop
> cd ../..
> 
> # Mesh extraction
> cd ext/nksr-cuda
> python setup.py develop
> cd ../..
> ```

直接在 xcube 的根目录下执行，不过要把一行进行修改：
`rm fvdb/setup.py && cp ../assets/setup.py openvdb/fvdb/` to
rm fvdb/setup.py && cp ../assets/setup.py fvdb/
