### ISSUE TITLE
ModuleNotFoundError: No module named 'xcube'

### ISSUE THREAD

**Issue by StarsTesla** [nv-tlabs/XCube#21]
I follow the instructions and download the waymo.tar, but I met this error.

`    from xcube.utils.vis_util import random_seed, waymo_palette, waymo_mapping
ModuleNotFoundError: No module named 'xcube'
`

**Comment by xrenaa** [comment]
Hi, please make sure you are running the job under the main directory.

**Comment by ryanhlewis** [comment]
@StarsTesla I had the same error, you easily fix it by adding XCube's directory to your Python path.

`export PYTHONPATH=$PYTHONPATH:/XCube`

if XCube is in your root (i.e. Docker), otherwise, set that path to where you cloned the repo.
