### ISSUE TITLE
mesh extraction setup error: x86_64-conda-linux-gnu-c++: error: unrecognized command-line option '-march'

### ISSUE THREAD

**Issue by wenqsun** [nv-tlabs/XCube#6]
Thanks for your guidelines! I followed the provided instructions and also copied the files as @rfeinman has mentioned before in #2 , but I met a problem:
`x86_64-conda-linux-gnu-c++: error: unrecognized command-line option '-march'`
It seems that the c++ version is not suitable, how can I fix this bug?

Thanks for your help!

**Comment by heiwang1997** [comment]
Hi @wenqsun could you maybe share your operating system and hardware details, as well as the output from `conda list`? Thanks!

**Comment by wenqsun** [comment]
The CUDA Driver Version is 12.1, the OS is Ubuntu 20.04 LTS, and the versions for my related package installation are listed below as a reference:

![image](https://github.com/nv-tlabs/XCube/assets/93043187/fe83ee95-3683-41d3-913e-ae012b25fd46)

![image](https://github.com/nv-tlabs/XCube/assets/93043187/01431fae-e9b0-43d6-8a6d-d57a09e23b21)

![image](https://github.com/nv-tlabs/XCube/assets/93043187/644edb88-efcf-47f5-8831-2429dfe548c2)

If you need more information, please let me know. Thank you!

**Comment by heiwang1997** [comment]
It seems that `gxx_linux-64` is not listed in your specifications? In that case could you try install the conda envinoments using `conda env update -f environment.yml`?

**Comment by wenqsun** [comment]
Sorry that I forget to provide the information about `gxx_linux-64`. I have installed the `gxx_linux-64`
![image](https://github.com/nv-tlabs/XCube/assets/93043187/637656c8-3981-4dd1-886f-326dafd6ecb4)

Also, the output of `which x86_64-conda-linux-gnu-c++` is `my_path/envs/xcube/bin/x86_64-conda-linux-gnu-c++`, and the version output is `x86_64-conda-linux-gnu-c++ (conda-forge gcc 11.4.0-13) 11.4.0`.

**Comment by heiwang1997** [comment]
I see this is really weird... I originally thought you might be running a wrong version of g++ under a wrong conda environment. But now it seems that everything should be correct.

Then I don't know the reason because I could not reproduce this from my side. Perhaps other can help?

**Comment by wenqsun** [comment]
OK. Thanks for your help! I will reinstall the environment and try to find out the problems.
