### ISSUE TITLE
How to provide the user-guided edited voxel grid as input

### ISSUE THREAD

**Issue by tanghaotommy** [nv-tlabs/XCube#9]
Dear authors, 

I found the idea of user-guided editing very interesting and would like to try the example showed in Figure 6.  I can build the voxel grid using Goxel, but the input to the diffusion model is a grid with normal as features. How do I get the normal from the voxel grid? I am new to this field, sorry if the answer is obvious. Thank you!

**Comment by xrenaa** [comment]
Hi, for that experiments, we trained a model without normal as condition. 
For easier editing, you could try to train a sparse VAE from 16 -> 128 and then train a 16x16x16 sparse Diffusion model. Then you could play with this sparse diffusion model and change the condition to it by Goxel.

**Comment by tanghaotommy** [comment]
Thanks a lot for the information! I'll give it a try and reach back if I may have other questions.

**Comment by zzz5y** [comment]
> Thanks a lot for the information! I'll give it a try and reach back if I may have other questions.

Hello do you have try it?I want to do this.But i still a little confused.Can we just use the checkpoint weight to guided?
